package governance.plugin;

/**
 * Create SOAP messages/request required to create "Module"  and 
 * assets and related assets in Governance Registry.
 */
public class GovernanceSOAPMessageCreator {

	public static String  createAddModuleRequest(String name, String version, String path){
		StringBuffer soapRequest = new StringBuffer();
		soapRequest.append("<soapenv:Envelope xmlns:soapenv='http://schemas.xmlsoap.org/soap/envelope/' ");
		soapRequest.append("xmlns:ser='http://services.add.module.governance.carbon.wso2.org'>");
		soapRequest.append("<soapenv:Header/>");
		soapRequest.append("<soapenv:Body>");
		soapRequest.append("<ser:addModule>");
		soapRequest.append("<ser:info><![CDATA[<metadata xmlns='http://www.wso2.org/governance/metadata'><overview><name>");
		soapRequest.append(name);
		soapRequest.append("</name><version>");
		soapRequest.append(version);
		soapRequest.append("</version><description>generated by maven-governance-plugin</description><sourcePath>");
		soapRequest.append(path);
		soapRequest.append("</sourcePath></overview></metadata>]]></ser:info>");
		soapRequest.append("</ser:addModule>");
		soapRequest.append("</soapenv:Body>");
		soapRequest.append("</soapenv:Envelope>");
		return soapRequest.toString();
	}
	
	public static String createGetArtifactContentRequest(String path){
		StringBuffer soapRequest = new StringBuffer();
		soapRequest.append("<soapenv:Envelope xmlns:soapenv='http://schemas.xmlsoap.org/soap/envelope/' ");
		soapRequest.append("xmlns:ser='http://services.generic.governance.carbon.wso2.org'>");
		soapRequest.append("<soapenv:Header/>");
		soapRequest.append("<soapenv:Body>");
		soapRequest.append("<ser:getArtifactContent>");
		soapRequest.append("<ser:path>");
		soapRequest.append(path);
		soapRequest.append("</ser:path>");
		soapRequest.append("</ser:getArtifactContent>");
		soapRequest.append("</soapenvBody>");
		soapRequest.append("</soapenv:Envelope>");
		return soapRequest.toString();

	}
	
	public static String createAddDependencyRequest(String groupId, String artifactId, String version){
		StringBuffer soapRequest = new StringBuffer();
		soapRequest.append("<soapenv:Envelope xmlns:soapenv='http://schemas.xmlsoap.org/soap/envelope/' ");
		soapRequest.append("xmlns:ser='http://services.add.dependency.governance.carbon.wso2.org'>");
        soapRequest.append("<soapenv:Header/>");
        soapRequest.append("<soapenv:Body>");
        soapRequest.append("<ser:addDependency>");   
        soapRequest.append("<ser:info>");
        soapRequest.append("<![CDATA[<metadata xmlns='http://www.wso2.org/governance/metadata'><overview><group>");
        soapRequest.append(groupId);
        soapRequest.append("</group><artifact>");
        soapRequest.append(artifactId);
        soapRequest.append("</artifact>");
        if ((version != null) && (!version.isEmpty())){
            soapRequest.append("<version>");
            soapRequest.append(version);
            soapRequest.append("</version>");
        }
        soapRequest.append("<approved>FALSE</approved></overview></metadata>]]>");
        soapRequest.append("</ser:info>");
        soapRequest.append("</ser:addDependency>");
        soapRequest.append("</soapenv:Body>");
		soapRequest.append("</soapenv:Envelope>");
		return soapRequest.toString();
	}
	
	public static String createAddAssociationRequst(String sourcePath, String destinationPath, String type, String todo){
		StringBuffer soapRequest = new StringBuffer();
		soapRequest.append("<soapenv:Envelope xmlns:soapenv='http://schemas.xmlsoap.org/soap/envelope/' ");
		soapRequest.append("xmlns:ser='http://services.relations.registry.carbon.wso2.org'>");
		soapRequest.append("<soapenv:Header/>");
        soapRequest.append("<soapenv:Body>");
        soapRequest.append("<ser:addAssociation><ser:path>");
        soapRequest.append(sourcePath);
        soapRequest.append("</ser:path><ser:type>");
        soapRequest.append(type);
        soapRequest.append("</ser:type><ser:associationPaths>");
        soapRequest.append(destinationPath);
        soapRequest.append("</ser:associationPaths><ser:todo>");
        soapRequest.append(todo);
        soapRequest.append("</ser:todo></ser:addAssociation>");
        soapRequest.append("</soapenv:Body>");
        soapRequest.append("</soapenv:Envelope>");
        return soapRequest.toString();
	}
}
